import json
"""
Report Generator — Media Intelligence Agent
Assembles the final Markdown report from AgentState data.

What this module does:
    Takes the fully populated AgentState (after all nodes have run)
    and assembles it into a structured, professional Markdown report.

    All formatting and assembly logic lives here.
    The report_node in nodes.py is a thin wrapper that calls generate_report().

Separation of concerns:
    - template.py  defines WHAT sections exist and their metadata
    - generator.py defines HOW to format each section
    - nodes.py     calls generate_report() and stores result in state
"""
import os
from datetime import date
from openai import OpenAI
from dotenv import load_dotenv

from src.report.template import (
    SCORECARD_DIMENSIONS,
    METHODOLOGY_TEXT,
)

load_dotenv()

_openai   = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
LLM_MODEL = "gpt-4o-mini"


# ── Section formatters ────────────────────────────────────

def format_header(outlet: str, competitors: list[str]) -> str:
    """Format the report title and metadata block."""
    benchmarked = ", ".join(competitors) if competitors else "none identified"
    return "\n".join([
        f"# Media Intelligence Brief: {outlet}",
        f"*Generated by Media Intelligence Agent | {date.today()}*",
        f"*Benchmarked against: {benchmarked}*",
        "",
        "---",
    ])


def generate_executive_summary(
    outlet: str,
    competitors: list[str],
    scores: dict,
    research_findings: str,
) -> str:
    """
    Generate a comprehensive one-page executive summary with 5 structured sections.

    Args:
        outlet:             Target outlet name
        competitors:        List of competitor names
        scores:             Full scores dict from consensus_scoring_node
        research_findings:  Raw research text for the target outlet

    Returns:
        Structured Markdown summary with sections and cross-references.
    """
    from src.scoring.dimensions import SCORING_DIMENSIONS

    target_scores  = scores.get(outlet, {})
    target_overall = target_scores.get("overall_score", "N/A")

    # Build competitor score comparison
    comp_lines = []
    for comp in competitors:
        comp_overall = scores.get(comp, {}).get("overall_score", "N/A")
        comp_lines.append(f"  - {comp}: {comp_overall}/5")
    comp_comparison = "\n".join(comp_lines)

    # Build dimension scores for target
    dim_lines = []
    for dim_key, dim_meta in SCORING_DIMENSIONS.items():
        dim_data  = target_scores.get(dim_key, {})
        dim_score = dim_data.get("score", "N/A")
        dim_alpha = dim_data.get("alpha", 0)
        dim_lines.append(f"  - {dim_meta['label']}: {dim_score}/5 (α={dim_alpha:.2f})")
    dim_summary = "\n".join(dim_lines)

    prompt = f"""You are a senior media industry analyst writing an executive summary for a competitive intelligence brief.

TARGET OUTLET: {outlet}
OVERALL SCORE: {target_overall}/5

COMPETITOR SCORES:
{comp_comparison}

DIMENSION SCORES FOR {outlet}:
{dim_summary}

RESEARCH FINDINGS (excerpt):
{research_findings[:1200]}

Write a comprehensive executive summary with exactly these 5 sections. Use Markdown formatting.
Each section should be 3-5 sentences minimum. Be specific, analytical, and evidence-based.
Reference actual data from the scores and findings. Do not use filler phrases.

Use this exact structure:

### What is being analysed
Describe {outlet} -- its ownership, editorial mission, audience, geographic reach, and market position. Explain why it matters in the competitive landscape and what makes it distinctive as a media outlet.

### Key findings
Summarise the most important findings from this benchmark. Lead with the overall score in context, then highlight 2-3 standout dimensions (highest and lowest scoring). Compare directly against {", ".join(competitors)}.

### Competitive position
How does {outlet} stand relative to its competitors? Where does it lead, where does it lag? What is the competitive gap and what does it mean strategically?

### Editorial drift
What topics are emerging, fading, or stable in {outlet}'s editorial focus? What does this reveal about the outlet's strategic direction and audience priorities?

### Strategic implications
What should a media strategist, investor, or publisher conclude from this report? What are the 2-3 most actionable insights? What risks or opportunities does this benchmark reveal?

End with: *See [Competitive Scorecard](#competitive-scorecard), [Competitive Position Analysis](#competitive-position-analysis), and [Outlet Analysis](#outlet-analysis) sections for full detail.*"""

    try:
        response = _openai.chat.completions.create(
            model=LLM_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.4,
            max_tokens=900,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"[generator] Executive summary error: {e}")
        return (
            f"{outlet} achieved an overall score of {target_overall}/5 in this "
            f"competitive benchmark against {', '.join(competitors)}. "
            "See detailed findings below."
        )


def format_scorecard(scores: dict, outlets: list[str]) -> str:
    """
    Format the comparative scorecard as a Markdown table.

    Args:
        scores:  Full scores dict {outlet_name: OutletScores}
        outlets: Ordered list of outlet names (target first)

    Returns:
        Markdown table string.
    """
    lines = [
        "> **Scoring:** 1–5 scale | **α** = Krippendorff's Alpha",
        "> 🔍 = Analytically contested (α < 0.4) — genuine expert disagreement, not a failure",
        "",
    ]

    # Header row
    header = "| Dimension | " + " | ".join(outlets) + " |"
    sep    = "|-----------|" + ":----------:|" * len(outlets)
    lines += [header, sep]

    # One row per dimension
    for dim_key, dim_label in SCORECARD_DIMENSIONS:
        row = f"| **{dim_label}** "
        for outlet in outlets:
            dim_data = scores.get(outlet, {}).get(dim_key, {})
            score    = dim_data.get("score", "—")
            alpha    = dim_data.get("alpha", 0)
            level    = dim_data.get("level", "")
            flagged  = dim_data.get("flagged", False)
            flag     = " 🔍" if flagged else ""
            tag      = "✓" if alpha == 1.0 else f"α={alpha:.2f}"
            row += f"| {score}/5 ({tag}){flag} "
        lines.append(row + "|")

    # Overall score row
    overall_row = "| **Overall** "
    for outlet in outlets:
        overall = scores.get(outlet, {}).get("overall_score", "—")
        overall_row += f"| **{overall}/5** "
    lines.append(overall_row + "|")

    return "\n".join(lines)


def format_drift_analysis(drift: dict, outlet: str) -> str:
    """
    Format the enriched temporal drift analysis for one outlet.
    Includes article examples with URLs for every topic cluster.
    """
    d = drift.get(outlet, {})
    if not d:
        return "*Drift analysis not available for this outlet.*"

    volumes = d.get("volume_change", {})
    lines   = []

    # Volume summary
    lines.append(
        f"**Article volume (GDELT + Guardian):** "
        f"{volumes.get('30d', 0)} articles (last 30d) · "
        f"{volumes.get('90d', 0)} (90d) · "
        f"{volumes.get('180d', 0)} (180d)"
    )
    lines.append("")

    # Wayback snapshot links
    wb_snapshots = d.get("wayback_snapshots", [])
    if wb_snapshots:
        lines.append("**Historical web presence (Wayback Machine):**")
        for snap in wb_snapshots:
            lines.append(
                f"- [{snap['months_ago']}mo ago snapshot]({snap['archive_url']}) "
                f"— {snap['date']}"
            )
        lines.append("")

    # Emerging topics with article examples
    emerging = d.get("emerging_with_examples", [])
    if not emerging:
        emerging = [{"topic": t, "examples": []} for t in d.get("emerging", [])]

    if emerging:
        lines.append("**↑ Emerging topics** *(new in last 30 days):*")
        lines.append("")
        for item in emerging:
            topic    = item.get("topic", "")
            examples = item.get("examples", [])
            lines.append(f"**{topic}**")
            for ex in examples[:3]:
                title = ex.get("title", "")
                url   = ex.get("url", "")
                date  = ex.get("date", "")
                if url:
                    lines.append(f"  - [{title}]({url}) — {date}")
                else:
                    lines.append(f"  - {title} — {date}")
            if not examples:
                lines.append("  - *No article examples retrieved*")
            lines.append("")

    # Fading topics with article examples
    fading = d.get("fading_with_examples", [])
    if not fading:
        fading = [{"topic": t, "examples": []} for t in d.get("fading", [])]

    if fading:
        lines.append("**↓ Fading topics** *(strong 6 months ago, declining now):*")
        lines.append("")
        for item in fading:
            topic    = item.get("topic", "")
            examples = item.get("examples", [])
            lines.append(f"**{topic}**")
            for ex in examples[:2]:
                title = ex.get("title", "")
                url   = ex.get("url", "")
                date  = ex.get("date", "")
                if url:
                    lines.append(f"  - [{title}]({url}) — {date}")
                else:
                    lines.append(f"  - {title} — {date}")
            if not examples:
                lines.append("  - *No recent examples (topic has declined)*")
            lines.append("")

    # Stable core
    stable = d.get("stable", [])
    if stable:
        lines.append("**→ Stable editorial core** *(consistent across all windows):*")
        for topic in stable:
            lines.append(f"- {topic}")
        lines.append("")

    # Analyst interpretation
    if d.get("interpretation"):
        lines.append(f"**Analyst interpretation:** {d['interpretation']}")

    return "\n".join(lines)


def format_outlet_section(
    outlet: str,
    is_target: bool,
    research: dict,
    drift: dict,
    rag_context: dict,
    scores: dict,
) -> str:
    """
    Format the full section for one outlet (target or competitor).

    Args:
        outlet:     Outlet name
        is_target:  True if this is the target outlet (not a competitor)
        research:   raw_research dict from state
        drift:      drift_results dict from state
        rag_context: rag_context dict from state
        scores:     scores dict from state

    Returns:
        Complete outlet section as Markdown string.
    """
    label    = "🎯 TARGET" if is_target else "📊 COMPETITOR"
    findings = research.get(outlet, {}).get("findings", "*No research findings available.*")
    context  = rag_context.get(outlet, "*No RAG context available.*")

    # Score summary with evidence for this outlet
    outlet_scores = scores.get(outlet, {})
    score_lines   = []
    for dim_key, dim_label in SCORECARD_DIMENSIONS:
        dim_data = outlet_scores.get(dim_key, {})
        if dim_data:
            score     = dim_data.get("score", "—")
            level     = dim_data.get("level", "—")
            alpha     = dim_data.get("alpha", 0)
            flag      = " 🔍" if dim_data.get("flagged") else ""
            reasoning = dim_data.get("reasoning", "")
            evidence  = dim_data.get("evidence", [])

            # Show CONSENSUS when alpha=1.0 (all evaluators agree exactly)
            display_level = "CONSENSUS" if alpha == 1.0 else level
            score_lines.append(f"#### {dim_label}: {score}/5 (α={alpha:.2f}, {display_level}){flag}")
            if reasoning:
                score_lines.append(f"*{reasoning}*")
            score_lines.append("")
            if evidence:
                score_lines.append("**Supporting evidence:**")
                for ev in evidence[:4]:
                    fact = ev.get("fact", "")
                    url  = ev.get("url", "")
                    if url and url.startswith("http"):
                        score_lines.append(f"- {fact} — [source]({url})")
                    else:
                        score_lines.append(f"- {fact}")
            score_lines.append("")

    lines = [
        f"## {outlet} {label}",
        "",
        "### Dimension Scores",
        "",
    ]
    lines += score_lines
    lines += [
        "",
        "### Research Findings",
        "",
        findings[:2000],  # cap at 2000 chars to keep report readable
        "",
        "### Temporal Drift Analysis",
        "",
        format_drift_analysis(drift, outlet),
        "",
        "### Industry Context (RAG)",
        "",
        context[:1000],  # cap at 1000 chars
        "",
        "---",
        "",
    ]

    return "\n".join(lines)


def format_flagged_section(scores: dict, outlets: list[str]) -> str | None:
    """
    Format the flagged dimensions section.
    Returns None if no dimensions are flagged.
    """
    flagged = []
    for outlet in outlets:
        for dim_key, dim_label in SCORECARD_DIMENSIONS:
            dim_data = scores.get(outlet, {}).get(dim_key, {})
            if isinstance(dim_data, dict) and dim_data.get("flagged"):
                flagged.append(f"- **{outlet}** — {dim_label} "
                               f"(α={dim_data.get('alpha', '?'):.2f})")

    if not flagged:
        return None

    lines = [
        "## 🔍 Analytically Contested Dimensions",
        "",
        "The following dimensions showed significant divergence across evaluator perspectives (α < 0.4).",
        "This is not a scoring failure — it reflects genuine expert disagreement.",
        "These are the most nuanced aspects of the outlet's positioning and warrant analyst judgment:",
        "",
    ]
    lines += flagged
    lines += ["", "---", ""]
    return "\n".join(lines)


# ── Main assembler ────────────────────────────────────────

def generate_report(state: dict) -> str:
    """
    Assemble the complete Markdown report from AgentState data.

    Args:
        state: The fully populated AgentState after all nodes have run.

    Returns:
        Complete report as a Markdown string.
    """
    outlet      = state["outlet_name"]
    outlets     = state["all_outlets"]
    competitors = state.get("competitors", [])
    scores      = state.get("scores", {})
    drift       = state.get("drift_results", {})
    research    = state.get("raw_research", {})
    rag_context = state.get("rag_context", {})

    print(f"[generator] Assembling report for '{outlet}'")

    sections = []

    # 1. Header
    sections.append(format_header(outlet, competitors))
    sections.append("")

    # 2. Executive Summary
    print("[generator] Generating executive summary...")
    findings_text = research.get(outlet, {}).get("findings", "")
    exec_summary  = generate_executive_summary(outlet, competitors, scores, findings_text)
    sections += ["## Executive Summary", "", exec_summary, "", "---", ""]

    # 3. Competitive Scorecard
    sections += ["## Competitive Scorecard", "", format_scorecard(scores, outlets), "", "---", ""]

    # 4. Competitive Position (new -- cross-outlet analysis)
    print("[generator] Generating competitive position analysis...")
    comp_position = generate_competitive_position(outlet, outlets, scores, research, drift)
    sections += [
        "## Competitive Position Analysis",
        "",
        f"*{outlet} benchmarked against {', '.join(competitors)}*",
        "",
        comp_position,
        "---",
        "",
    ]

    # 5. Per-outlet sections
    for o in outlets:
        is_target = (o == outlet)
        section   = format_outlet_section(o, is_target, research, drift, rag_context, scores)
        sections.append(section)

    # 7. Flagged dimensions (only if any exist)
    flagged_section = format_flagged_section(scores, outlets)
    if flagged_section:
        sections.append(flagged_section)

    # 6. Methodology
    sections += ["## Methodology", "", METHODOLOGY_TEXT, ""]

    report = "\n".join(sections)
    print(f"[generator] ✓ Report assembled: {len(report)} chars")
    return report


def save_report(report: str, outlet_name: str) -> str:
    """
    Save a report to the /reports/ folder.

    Args:
        report:      Report Markdown string
        outlet_name: Outlet name (used as filename)

    Returns:
        Path to the saved file.
    """
    os.makedirs("reports", exist_ok=True)
    filename = outlet_name.lower().replace(" ", "_").replace("/", "_")
    filepath = f"reports/{filename}.md"

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"[generator] Report saved: {filepath}")
    return filepath


def generate_competitive_position(
    target_outlet: str,
    all_outlets: list[str],
    scores: dict,
    research: dict,
    drift: dict,
) -> str:
    """
    Generate a rich competitive position section answering 5 key questions:
    1. Market position (who leads?)
    2. Editorial differentiation (what makes each outlet unique?)
    3. Reputation signals (how does journalism community see each outlet?)
    4. Trajectory (growing, stable, or declining?)
    5. Strategic vulnerabilities and opportunities

    This is a cross-outlet comparison -- all 3 outlets analysed together.
    """
    competitors = [o for o in all_outlets if o != target_outlet]

    # Build cross-outlet context for the LLM
    outlet_summaries = []
    for outlet in all_outlets:
        findings  = research.get(outlet, {}).get("findings", "")[:800]
        overall   = scores.get(outlet, {}).get("overall_score", "N/A")
        drift_d   = drift.get(outlet, {})
        emerging  = drift_d.get("emerging", [])[:4]
        volume    = drift_d.get("volume_change", {})

        outlet_summaries.append(
            f"=== {outlet} ===\n"
            f"Overall score: {overall}/5\n"
            f"Emerging topics: {emerging}\n"
            f"Article volume: 30d={volume.get('30d',0)}, 90d={volume.get('90d',0)}\n"
            f"Research: {findings}"
        )

    cross_context = "\n\n".join(outlet_summaries)

    prompt = f"""You are a senior media industry analyst. Analyse the competitive position of {target_outlet} 
against its competitors: {', '.join(competitors)}.

Data for all outlets:
{cross_context}

Write a competitive position analysis with EXACTLY these 5 sections.
For each section, provide specific, comparative, evidence-based analysis.
Include concrete facts, numbers, and examples where available.
Do NOT be vague or generic.

Return as JSON with these exact keys:
{{
  "market_position": {{
    "assessment": "LEADING|CHALLENGING|FOLLOWING",
    "confidence": "HIGH|MODERATE|LOW",
    "analysis": "<2-3 sentences with specific comparative data>",
    "evidence": [
      {{"fact": "<specific fact>", "url": "<url or empty>"}},
      {{"fact": "<specific fact>", "url": "<url or empty>"}}
    ]
  }},
  "editorial_differentiation": {{
    "unique_to_target": ["<topic or approach unique to {target_outlet}>"],
    "gaps_vs_competitors": ["<topic competitors cover that target doesn't>"],
    "analysis": "<2-3 sentences>",
    "evidence": [{{"fact": "<fact>", "url": ""}}]
  }},
  "reputation_signals": {{
    "assessment": "<how journalism community perceives {target_outlet}>",
    "vs_competitors": "<how this compares to competitor perception>",
    "evidence": [{{"fact": "<fact>", "url": ""}}]
  }},
  "trajectory": {{
    "direction": "IMPROVING|STABLE|DECLINING",
    "confidence": "HIGH|MODERATE|LOW",
    "analysis": "<2-3 sentences with volume and score data>",
    "evidence": [{{"fact": "<fact>", "url": ""}}]
  }},
  "strategic": {{
    "vulnerabilities": ["<specific vulnerability vs competitors>"],
    "opportunities": ["<specific opportunity vs competitors>"]
  }}
}}"""

    try:
        response = _openai.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=1500,
        )
        raw = response.choices[0].message.content.strip()
        if "```" in raw:
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        data = json.loads(raw)
    except Exception as e:
        print(f"[generator] Competitive position error: {e}")
        return f"*Competitive position analysis unavailable: {str(e)}*"

    # Format the structured output as rich Markdown
    lines = []

    # Market position
    mp = data.get("market_position", {})
    if mp:
        conf  = mp.get("confidence", "")
        pos   = mp.get("assessment", "")
        lines += [
            f"### Market Position: **{pos}** *(confidence: {conf})*",
            "",
            mp.get("analysis", ""),
            "",
        ]
        for ev in mp.get("evidence", [])[:3]:
            fact = ev.get("fact", "")
            url  = ev.get("url", "")
            if url and url.startswith("http"):
                lines.append(f"- {fact} — [source]({url})")
            else:
                lines.append(f"- {fact}")
        lines.append("")

    # Editorial differentiation
    ed = data.get("editorial_differentiation", {})
    if ed:
        lines += ["### Editorial Differentiation", "", ed.get("analysis", ""), ""]
        if ed.get("unique_to_target"):
            lines.append(f"**Unique to {target_outlet}:**")
            for item in ed["unique_to_target"]:
                lines.append(f"- {item}")
            lines.append("")
        if ed.get("gaps_vs_competitors"):
            lines.append("**Coverage gaps vs competitors:**")
            for item in ed["gaps_vs_competitors"]:
                lines.append(f"- {item}")
            lines.append("")

    # Reputation signals
    rep = data.get("reputation_signals", {})
    if rep:
        lines += [
            "### Reputation Signals",
            "",
            rep.get("assessment", ""),
            "",
            f"**vs competitors:** {rep.get('vs_competitors', '')}",
            "",
        ]
        for ev in rep.get("evidence", [])[:2]:
            fact = ev.get("fact", "")
            url  = ev.get("url", "")
            if url and url.startswith("http"):
                lines.append(f"- {fact} — [source]({url})")
            else:
                lines.append(f"- {fact}")
        lines.append("")

    # Trajectory
    traj = data.get("trajectory", {})
    if traj:
        direction = traj.get("direction", "")
        conf      = traj.get("confidence", "")
        lines += [
            f"### Trajectory: **{direction}** *(confidence: {conf})*",
            "",
            traj.get("analysis", ""),
            "",
        ]
        for ev in traj.get("evidence", [])[:2]:
            fact = ev.get("fact", "")
            url  = ev.get("url", "")
            if url and url.startswith("http"):
                lines.append(f"- {fact} — [source]({url})")
            else:
                lines.append(f"- {fact}")
        lines.append("")

    # Strategic vulnerabilities and opportunities
    strat = data.get("strategic", {})
    if strat:
        lines += ["### Strategic Assessment", ""]
        if strat.get("vulnerabilities"):
            lines.append("**Vulnerabilities vs competitors:**")
            for v in strat["vulnerabilities"]:
                lines.append(f"- ⚠️ {v}")
            lines.append("")
        if strat.get("opportunities"):
            lines.append("**Opportunities vs competitors:**")
            for o in strat["opportunities"]:
                lines.append(f"- ✓ {o}")
            lines.append("")

    return "\n".join(lines)


def save_to_notion(state: dict, report: str, report_url: str = "") -> str | None:
    """
    Save the report to Notion after generation.
    Returns the Notion page URL or None if Notion is not configured.
    """
    try:
        from src.integrations.notion_client import save_report_to_notion
        notion_url = save_report_to_notion(
            outlet_name = state["outlet_name"],
            report      = report,
            scores      = state.get("scores", {}),
            competitors = state.get("competitors", []),
            report_url  = report_url,
        )
        return notion_url
    except Exception as e:
        print(f"[generator] Notion save skipped: {e}")
        return None
